version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres: